root = "."
tmp_dir = "tmp"

[build]
cmd = "make dev-build"
bin = "./bin/mapd"
include_ext = ["go"]
exclude_dir = ["bin", "tmp", "vendor"]
delay = 1000
stop_on_error = false
send_interrupt = true
kill_delay = 500
